[tool.poetry]
name = "ot-harjoitustyo"
version = "0.1.0"
description = ""
authors = ["J-Uhero <juho.herranen@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
invoke = "^1.5.0"
pygame = "^2.0.1"
python-dotenv = "^0.17.0"
pygame-gui = "^0.5.7"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
pytest = "^6.2.3"
pylint = "^2.7.4"
autopep8 = "^1.5.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
